name: ROS Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up ROS
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL http://repo.ros2.org/repos.key | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu focal main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-foxy-ros-base python3-colcon-common-extensions
        sudo apt install -y python3-rosdep
        sudo rosdep init
        rosdep update
    - name: Install dependencies using rosdep
      run: rosdep install --from-paths src --ignore-src -r -y
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==8.0.0
    - name: Add pytest to PATH
      run: echo "$HOME/.local/lib/ebva_mapless" >> $GITHUB_PATH
    - name: Run tests
      run: pytest test
