name: ROS2 Lint

on: push

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-eloquent-ros-base-latest
      options: -u root  # setup-node requires root access
    strategy:
      fail-fast: false
      matrix:
          linter: [flake8, pep257, pep8, xmllint]
    steps:
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6=2.28-10
    - run: sudo chown -R rosbuild:rosbuild .
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        package-name: mapless_control
